### ISSUE TITLE
Toolchain Link not working anymore

### ISSUE THREAD

**Issue by berkutta** [MediaDeb/MediaDeb#5]
Is there an alternative link to download the toolchain?

```
-- Downloading...
   dst='/data/tarballs/path=%2F&files=arm-module-linux-gnueabi.tgz'
   timeout='none'
-- Using src='https://cloud.ncrmnt.org/index.php/s/7hYjCqbJgMcVYFe/download?path=%2F&files=arm-module-linux-gnueabi.tgz'
-- Retrying...
-- Using src='https://cloud.ncrmnt.org/index.php/s/7hYjCqbJgMcVYFe/download?path=%2F&files=arm-module-linux-gnueabi.tgz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://cloud.ncrmnt.org/index.php/s/7hYjCqbJgMcVYFe/download?path=%2F&files=arm-module-linux-gnueabi.tgz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://cloud.ncrmnt.org/index.php/s/7hYjCqbJgMcVYFe/download?path=%2F&files=arm-module-linux-gnueabi.tgz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://cloud.ncrmnt.org/index.php/s/7hYjCqbJgMcVYFe/download?path=%2F&files=arm-module-linux-gnueabi.tgz'
-- Retry after 60 seconds (attempt #5) ...
```

**Comment by nekromant** [comment]
@berkutta Thanks for pointing this out, I had a recent infrastructure update and all the links ceased to exist. I'll try to fix it this weekend.

**Comment by comradeFreeman** [comment]
Still unavailable..

**Comment by comradeFreeman** [comment]
> @berkutta Thanks for pointing this out, I had a recent infrastructure update and all the links ceased to exist. I'll try to fix it this weekend.

Still unavailable..

**Comment by nekromant** [comment]
Yeah, working on that. I had a huge rework of my homebrew infrastructure last year and many things were left buried somewhere in the backups.

**Comment by comradeFreeman** [comment]
> Yeah, working on that. I had a huge rework of my homebrew infrastructure last year and many things were left buried somewhere in the backups.

А Вы не могли бы временно залить архив `arm-module-linux-gnueabi.tgz` на файлообменник или диск?
Пытаюсь собрать более новый Debian 11, но из-за архива вся работа встала

**Comment by nekromant** [comment]
https://cloud.ncrmnt.org/s/2QsmjGQfBpDoQkA

Here's the updated link. I haven't yet updated the URLs in the scripts, will do it later. For now you can download everything manually

**Comment by comradeFreeman** [comment]
> https://cloud.ncrmnt.org/s/2QsmjGQfBpDoQkA
> 
> Here's the updated link. I haven't yet updated the URLs in the scripts, will do it later. For now you can download everything manually

Там в открытом доступе оказалась папка Cellphone с кучей фотографий и видео, это нормально?

**Comment by nekromant** [comment]
Спасибо, что заметил - мой эпичный косяк.

**Comment by ekubeev** [comment]
https://cloud.ncrmnt.org/s/2QsmjGQfBpDoQkA не доступно на скачивание....  Прошу перевыложить. 
Заранее спасибо.

**Comment by comradeFreeman** [comment]
> https://cloud.ncrmnt.org/s/2QsmjGQfBpDoQkA не доступно на скачивание.... Прошу перевыложить. Заранее спасибо.

Да нет, вроде работает, качается

**Comment by ekubeev** [comment]
> > https://cloud.ncrmnt.org/s/2QsmjGQfBpDoQkA не доступно на скачивание.... Прошу перевыложить. Заранее спасибо.
> 
> Да нет, вроде работает, качается

Реально стало качаться ... Час назад не работало :) Спасибо.
